### ISSUE TITLE
Obsługa tworzenie struktur zdefiniowanych przez użytkownika

### ISSUE THREAD

**Issue by PiorunPL** [PiorunPL/WireWorldJava#20]

**Comment by bastyje** [comment]
## Zrobione
- odczytywanie struktur zdefiniowanych przez użytkownika z pliku i ich tworzenie

## Do zrobienia
- [ ] zastanowić się, jak używać zdefiniowane przez użytkownika struktury, jak tworzyć ich kolejne instancje
- [ ] przejrzeć metodę Structure.isStructure()
- [ ] tworzenie struktur zdefiniowanych przez użytkownika w edytorze

**Comment by bastyje** [comment]
na razie zawieszam wykonanie tej funkcjonalności
