### ISSUE TITLE
Wczytywanie Danych z pliku - format 2 (strukturalny)

### ISSUE THREAD

**Issue by PiorunPL** [PiorunPL/WireWorldJava#3]
Wczytywanie danych z pliku w formacie strukturalnym

**Comment by bastyje** [comment]
## Zrobione do tej pory:
- zaprojektowany format struct pliku z danymi
- rozpoznawanie formatu pliku
- czytanie wymiarów mapy
- czytanie struktur zdefiniowanych przez użytkownika i zapisywanie ich do kontenera owych struktur

## Do zrobienia
- czytanie mapy, dokończyć testowanie
- poprawić metodę StructMap.equals(), żeby móc przeprowadzić testy
